apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: nw-dev
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: nw-dev-auth-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: formanceapi.intra.netwallet.dev # Your external domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc # Points to the Service above
                port:
                  number: 80
