apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
  namespace: ory-dev
  labels:
    "app.kubernetes.io/name": "hydra"
    "app.kubernetes.io/instance": "hydra"
    "app.kubernetes.io/version": "v26.2.0"
    "app.kubernetes.io/managed-by": "Helm"
    "helm.sh/chart": "hydra-0.61.1"
data:
  "hydra.yaml": |
    serve:
      admin:
        port: 4445
      public:
        port: 4444
      tls:
        allow_termination_from:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    urls:
      self: 
        issuer: http://localhost:4444/
      login: http://localhost:4433/self-service/login/browser
      consent: http://localhost:4433/self-service/consent/browser
