apiVersion: v1
kind: Service
metadata:
  name: hydra-admin
  namespace: ory-dev
  labels:
    "app.kubernetes.io/name": "hydra"
    "app.kubernetes.io/instance": "hydra"
    "app.kubernetes.io/version": "v26.2.0"
    "app.kubernetes.io/managed-by": "Helm"
    "helm.sh/chart": "hydra-0.61.1"
    app.kubernetes.io/component: admin
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 4445
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
